import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GENPOS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
        <div className="w-1/5 m-4 p-5 bg-stone-50">
          <h1 className="text-4xl font-bold p-2"> GENPOS</h1>
          
          <div className="m-4 font-bold">
          <div className="mt-4"><a href="">Dashboard</a></div>
          <div className="mt-4"><a href="">Purchase</a></div>
          <div className="dropdown mt-4 dropdown-bottom">
           <div tabIndex={0} role="button" className="btn text-l m-1">Business unit</div>
              <ul tabIndex={0} className="list-disc ml-4 menu rounded-box z-[1] w-52 p-2">
                <li className="mt-2"><a>Groups</a></li>
                <li className="mt-2"><a>Companies</a></li>
                <li className="mt-2"><a>Brands</a></li>
                <li className="mt-2"><a>Outlets</a></li>
                <li className="mt-2"><a>Warehouses</a></li>
              </ul>
          </div>
          <div className="mt-4"><a href="">Catalog</a></div>
          <div className="mt-4"><a href="">User</a></div>
          <div className="mt-4"><a href="">Configurations</a></div>
          <div className="mt-4"><a href="">System</a></div>
        </div>
      

        </div>
        <div className="w-4/5">
        <header>
          <div className="flex justify-between">
            <div className="flex m-4 w-1/3 relative"><input 
                    className="border-2 p-2 w-full rounded-lg outline-none" 
                    type="search"  
                    name="search"
                    placeholder="search"
                    value="Search your page..." />
                <button className="bg-blue-600 px-4 py-1 rounded-lg"> ⌘K</button>
            </div>
            <div className="flex m-4">
              <button className="bg-slate-200 p-2 m-2 rounded-lg">abc</button>
              <button className="bg-slate-200 p-2 m-2 rounded-lg">abc</button>
              <button className="bg-slate-200 p-2 m-2 rounded-lg">abc</button>
              <button className="bg-slate-200 p-2 m-2 rounded-lg">abc</button>
            </div>
          </div>
        </header>

        {children}
        </div>
        </div>
      </body>
    </html>
  );
}
